"use client"

import { useState, useTransition } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { Activity, ArrowRight, Backpack, Crown, History, Minus, Plus, RotateCcw, ScrollText, ShoppingBag, Sparkles, Swords, Target, Users, Zap } from "lucide-react"
import { toast } from "sonner"
import { addToInventoryAction, advanceTurnAction, applyStatusAction, createBattleAction, createCharacterAction, createEnemyAction, createItemAction, endBattleAction, grantExpAction, performAttackAction, purchaseAction, pullAction, resetPityAction, sellAction, setInventoryQuantityAction, setParticipantResourceAction, setPartyAction, undoEventAction, undoLastActionAction } from "@/lib/actions"
import type { Battle, Character, Currency, EnemyTemplate, GameEvent, GachaPoolEntry, InventoryEntry, Rarity, ShopEntry, StatusTemplate } from "@/lib/types"
import { fmt, RARITY_LABEL, RARITY_TEXT } from "@/lib/ui"

type Data = { characters: Character[]; enemies: EnemyTemplate[]; inventory: InventoryEntry[]; shop: ShopEntry[]; currencies: Currency[]; statuses: StatusTemplate[]; gacha: { config: any; cost: { currencyId: string; perPull: number }; pity: { pity4: number; pity5: number }; pool: GachaPoolEntry[] }; events: GameEvent[]; battle: Battle | null }
const titles: Record<string, string> = { dashboard: "Command deck", characters: "Characters", enemies: "Enemy codex", battle: "Battlefield", inventory: "Inventory", shop: "Supply exchange", gacha: "Summoning pool", history: "Event chronicle" }
const nav = [{ href: "/", label: "Command deck", icon: Activity }, { href: "/battle", label: "Battlefield", icon: Swords }, { href: "/characters", label: "Characters", icon: Users }, { href: "/enemies", label: "Enemy codex", icon: Target }, { href: "/inventory", label: "Inventory", icon: Backpack }, { href: "/shop", label: "Shop", icon: ShoppingBag }, { href: "/gacha", label: "Gacha", icon: Sparkles }, { href: "/history", label: "History", icon: ScrollText }]

function Bar({ value, max, tone = "hp" }: { value: number; max: number; tone?: "hp" | "tp" | "exp" }) { return <div className="h-1.5 overflow-hidden rounded-full bg-secondary"><div className={`h-full rounded-full ${tone === "hp" ? "bg-hp" : tone === "tp" ? "bg-tp" : "bg-exp"}`} style={{ width: `${Math.max(0, Math.min(100, max ? value / max * 100 : 0))}%` }} /></div> }
function Resource({ label, value, max, tone }: { label: string; value: number; max: number; tone: "hp" | "tp" | "exp" }) { return <div className="space-y-1"><div className="flex justify-between text-[10px] uppercase tracking-wider text-muted-foreground"><span>{label}</span><span className="tnum text-foreground">{fmt(value)} / {fmt(max)}</span></div><Bar value={value} max={max} tone={tone} /></div> }
function Panel({ title, icon: Icon, children }: { title: string; icon: any; children: React.ReactNode }) { return <section className="panel"><div className="panel-head"><div className="flex items-center gap-2"><Icon className="size-4 text-primary" /><h2>{title}</h2></div></div>{children}</section> }
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div> }
function eventTimestamp(value: number) { return new Date(value).toISOString().slice(11, 16) + ' UTC' }
function EventList({ events }: { events: any[] }) { return <div className="event-list">{events.length ? events.map(e => <div className="event" key={e.id}><span className="event-mark" /><div><p>{e.description}</p><span>{eventTimestamp(e.createdAt)} · {e.type}</span></div></div>) : <Empty text="No events recorded yet." />}</div> }

function EntityForm({ title, submit, onSubmit, onCancel }: { title: string; submit: string; onSubmit: (data: FormData) => void; onCancel: () => void }) {
  return <form className="entity-form" onSubmit={e => { e.preventDefault(); onSubmit(new FormData(e.currentTarget)); e.currentTarget.reset(); onCancel() }}><strong>{title}</strong><input className="field" name="name" required placeholder="Name" /><input className="field" name="level" type="number" min="1" max="120" defaultValue="1" aria-label="Level" /><select className="field" name="rarity" defaultValue="3" aria-label="Rarity">{[1,2,3,4,5].map(n => <option key={n} value={n}>{n} star</option>)}</select><input className="field" name="hp" type="number" min="1" defaultValue="1000" aria-label="HP" /><input className="field" name="atk" type="number" min="0" defaultValue="100" aria-label="ATK" /><input className="field" name="def" type="number" min="0" defaultValue="100" aria-label="DEF" /><button className="btn primary" type="submit">{submit}</button><button className="btn secondary" type="button" onClick={onCancel}>Cancel</button></form>
}
function formNumber(form: FormData, name: string) { return Number(form.get(name) || 0) }
function characterInput(form: FormData) { const hp = formNumber(form,"hp"); const atk = formNumber(form,"atk"); const def = formNumber(form,"def"); return { name: String(form.get("name") || "Character"), level: formNumber(form,"level"), rarity: formNumber(form,"rarity") as Rarity, isNpc: false, base: { hp, atk, def, critRate: 5, critDmg: 150, energyRegen: 100, basicBonus: 0, skillBonus: 0, ultimateBonus: 0, basicRes: 0, skillRes: 0, ultimateRes: 0, tp: 100 }, growth: { hp: 80, atk: 8, def: 6 }, tags: [], notes: "", inParty: false } }
function enemyInput(form: FormData) { const hp = formNumber(form,"hp"); const atk = formNumber(form,"atk"); const def = formNumber(form,"def"); return { name: String(form.get("name") || "Enemy"), level: formNumber(form,"level"), rarity: formNumber(form,"rarity") as Rarity, hp, atk, def, critRate: 5, critDmg: 150, basicRes: 0, skillRes: 0, ultimateRes: 0, basicBonus: 0, skillBonus: 0, ultimateBonus: 0, tp: 100, expReward: 100, abilities: [], loot: [], tags: [], notes: "" } }

export function Console({ section, data }: { section: string; data: Data }) {
  const router = useRouter(); const [pending, start] = useTransition(); const [query, setQuery] = useState("")
  const run = (job: () => Promise<unknown>, message = "State saved") => start(async () => { try { await job(); toast.success(message); router.refresh() } catch (e) { toast.error((e as Error).message) } })
  const q = query.toLowerCase()
  return <div className="app-frame"><aside className="side-nav"><div className="brand"><div className="brand-mark"><Crown /></div><div><strong>RPG</strong><small>GM CONTROL</small></div></div><nav>{nav.map(item => { const Icon = item.icon; const active = item.href === "/" ? section === "dashboard" : section === item.href.slice(1); return <Link className={active ? "active" : ""} href={item.href} key={item.href}><Icon />{item.label}</Link> })}</nav><div className="side-footer">LOCAL-FIRST<br /><span>SQLite campaign state</span></div></aside><main className="workspace"><header className="topbar"><div className="mobile-brand">RPG</div><div className="currency-strip">{data.currencies.map((currency, index) => <span key={currency.id}><span className={`currency-dot ${index === 0 ? "gold" : index === 1 ? "gem" : "orb"}`} />{fmt(currency.amount)} {currency.name}</span>)}</div></header><div className="content"><div className="heading"><div><p className="eyebrow">RPG / local campaign</p><h1>{titles[section] ?? "Command deck"}</h1><p className="subtitle">Persistent GM control for a living tabletop world.</p></div><div className="save-state"><span className={pending ? "status-dot pulse" : "status-dot"} />{pending ? "Writing…" : "All state saved"}</div></div>{section !== "dashboard" && section !== "battle" && <input className="field mb-5 max-w-md" placeholder={`Search ${titles[section] ?? "workspace"}…`} value={query} onChange={e => setQuery(e.target.value)} />}{section === "dashboard" && <Dashboard data={data} run={run} />}{section === "battle" && <BattleView data={data} run={run} />}{section === "characters" && <Characters data={data.characters.filter(c => c.name.toLowerCase().includes(q))} run={run} />}{section === "enemies" && <Enemies data={data.enemies.filter(e => e.name.toLowerCase().includes(q))} run={run} />}{section === "inventory" && <Inventory data={data.inventory.filter(i => i.item.name.toLowerCase().includes(q) || i.item.category.toLowerCase().includes(q))} run={run} goldCurrencyId={data.currencies.find(c => c.name === "Gold")?.id ?? "cur_gold"} />}{section === "shop" && <Shop data={data.shop} run={run} />}{section === "gacha" && <Gacha data={data} run={run} />}{section === "history" && <HistoryView events={data.events} run={run} />}</div></main></div>
}

function Dashboard({ data, run }: { data: Data; run: any }) { return <><div className="stat-grid"><div className="metric"><span>Party ready</span><strong>{data.characters.filter(c => c.inParty).length}</strong><small>active characters</small></div><div className="metric"><span>Inventory</span><strong>{data.inventory.reduce((n, i) => n + i.quantity, 0)}</strong><small>owned units</small></div><div className="metric"><span>5★ pity</span><strong>{data.gacha.pity.pity5}<em> / {data.gacha.config.pity5Threshold}</em></strong><small>toward guarantee</small></div><div className="metric"><span>Battle</span><strong>{data.battle ? `R${data.battle.round}` : "—"}</strong><small>{data.battle ? "active encounter" : "no active encounter"}</small></div></div><div className="two-col"><Panel title="Current party" icon={Users}>{data.characters.filter(c => c.inParty).map(c => <CharacterRow key={c.id} c={c} run={run} />)}{!data.characters.some(c => c.inParty) && <Empty text="Add a character to the party from Characters." />}</Panel><Panel title="Recent events" icon={History}><EventList events={data.events.slice(0, 7)} /></Panel></div><Panel title="Quick actions" icon={Zap}><div className="quick-grid"><Link className="quick" href="/battle"><Swords />Run battle<ArrowRight /></Link><Link className="quick" href="/inventory"><Backpack />Manage inventory<ArrowRight /></Link><Link className="quick" href="/gacha"><Sparkles />Roll gacha<ArrowRight /></Link><Link className="quick" href="/characters"><Users />Give EXP<ArrowRight /></Link></div></Panel></> }
function CharacterRow({ c, run }: { c: Character; run: any }) { return <div className="entity-row"><div className="avatar"><Crown className={RARITY_TEXT[c.rarity]} /></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between"><span className="truncate font-semibold">{c.name}</span><span className="tag">LV {c.level}</span></div><Resource label="HP" value={c.currentHp} max={c.maxHp} tone="hp" /><div className="mt-2"><Resource label="TP" value={c.currentTp} max={c.maxTp} tone="tp" /></div></div><button className="icon-btn" title="Give 100 EXP" onClick={() => run(() => grantExpAction(c.id, 100), "+100 EXP applied")}><Plus /></button></div> }

function BattleView({ data, run }: { data: Data; run: any }) {
  const b = data.battle
  const [attacker, setAttacker] = useState("")
  const [target, setTarget] = useState("")
  const [override, setOverride] = useState("")
  const [statusId, setStatusId] = useState(data.statuses[0]?.id ?? "")
  const [resourceValue, setResourceValue] = useState("")
  if (!b) return <StartBattle data={data} run={run} />

  const attackerId = attacker || b.participants.find(p => p.side === "player" && !p.defeated)?.id || ""
  const targetId = target || b.participants.find(p => p.side === "enemy" && !p.defeated)?.id || ""
  const active = b.participants.find(p => p.id === attackerId)
  const selected = b.participants.find(p => p.id === (target || attackerId))
  const template = data.statuses.find(s => s.id === statusId)

  return <>
    <div className="battle-toolbar"><div><p className="eyebrow">ROUND {b.round}</p><h2 className="text-lg font-semibold">{b.name}</h2></div><div className="flex gap-2"><button className="btn secondary" onClick={() => run(() => undoLastActionAction(b.id), "Last action undone")}><RotateCcw />Undo</button><button className="btn secondary" onClick={() => run(() => endBattleAction(b.id, true), "Battle ended and resources synced")}>End battle</button><button className="btn primary" onClick={() => run(() => advanceTurnAction(b.id), "Turn advanced")}><ArrowRight />Next turn</button></div></div>
    <div className="battle-sides"><div><div className="side-label"><Users /> PLAYER PARTY</div>{b.participants.filter(p => p.side === "player").map(p => <BattleCard key={p.id} p={p} selected={attackerId === p.id} onClick={() => setAttacker(p.id)} />)}</div><div><div className="side-label enemy"><Target /> ENEMY PARTY</div>{b.participants.filter(p => p.side === "enemy").map(p => <BattleCard key={p.id} p={p} selected={targetId === p.id} onClick={() => setTarget(p.id)} />)}</div></div>
    <Panel title={active ? `${active.name} combat controls` : "Select an attacker"} icon={Swords}>{active && <div className="ability-grid">{active.abilities.map(ab => <button className="ability" key={ab.id} disabled={!targetId || active.defeated} onClick={() => run(() => performAttackAction({ battleId: b.id, attackerId: active.id, targetId, abilityId: ab.id, overrideDamage: override ? Number(override) : null }), `${ab.name} resolved`)}><span>{ab.name}</span><small>{ab.attackType} · {ab.multiplier}% ATK{ab.tpCost ? ` · ${ab.tpCost} TP` : ""}</small></button>)}</div>}<div className="mt-4 flex flex-wrap items-center gap-2"><label className="text-xs text-muted-foreground">GM damage override</label><input className="field w-36" type="number" placeholder="calculated" value={override} onChange={e => setOverride(e.target.value)} /><span className="text-xs text-muted-foreground">Empty = automatic calculation</span></div></Panel>
    {selected && <Panel title={`Direct override · ${selected.name}`} icon={Zap}><div className="flex flex-wrap items-end gap-3"><label className="field-label">Set HP / TP<input className="field" type="number" value={resourceValue} onChange={e => setResourceValue(e.target.value)} placeholder={`${selected.currentHp} HP`} /></label><button className="btn secondary" disabled={!resourceValue} onClick={() => run(() => setParticipantResourceAction(b.id, selected.id, "hp", Number(resourceValue)), "HP overridden")}><Plus />Set HP</button><button className="btn secondary" disabled={!resourceValue} onClick={() => run(() => setParticipantResourceAction(b.id, selected.id, "tp", Number(resourceValue)), "TP overridden")}><Plus />Set TP</button>{template && <><label className="field-label">Apply status<select className="field" value={statusId} onChange={e => setStatusId(e.target.value)}>{data.statuses.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select></label><button className="btn primary" onClick={() => run(() => applyStatusAction({ battleId: b.id, participantId: selected.id, name: template.name, description: template.description, modifiers: template.modifiers, duration: template.defaultDuration, maxStacks: template.maxStacks, source: "GM" }), `${template.name} applied`)}>Apply status</button></>}</div></Panel>}
    <Panel title="Battle history" icon={History}><EventList events={b.actions.map(a => ({ id: a.id, type: "battle", description: a.description, createdAt: a.createdAt }))} /></Panel>
  </>
}
function BattleCard({ p, selected, onClick }: { p: any; selected: boolean; onClick: () => void }) { return <button className={`battle-card ${selected ? "selected" : ""} ${p.defeated ? "defeated" : ""}`} onClick={onClick}><div className="flex items-center justify-between"><span className="font-semibold">{p.name}</span><span className="tag">LV {p.level}</span></div><div className="mt-3"><Resource label="HP" value={p.currentHp} max={p.maxHp} tone="hp" /><div className="mt-2"><Resource label="TP" value={p.currentTp} max={p.maxTp} tone="tp" /></div></div>{p.statuses.length > 0 && <div className="mt-3 flex flex-wrap gap-1">{p.statuses.map((s: any) => <span className="tag status" key={s.id}>{s.name}</span>)}</div>}</button> }
function StartBattle({ data, run }: { data: Data; run: any }) { const [enemy, setEnemy] = useState(data.enemies[0]?.id ?? ""); const party = data.characters.filter(c => c.inParty); return <Panel title="Start encounter" icon={Swords}><p className="text-sm text-muted-foreground">Choose the current party and an enemy template. Battle state persists when you leave this page.</p><div className="mt-5 flex flex-wrap items-end gap-3"><label className="field-label">Enemy template<select className="field" value={enemy} onChange={e => setEnemy(e.target.value)}>{data.enemies.map(e => <option key={e.id} value={e.id}>{e.name} · LV {e.level}</option>)}</select></label><button className="btn primary" disabled={!party.length || !enemy} onClick={() => run(() => createBattleAction({ name: "Live encounter", characterIds: party.map(c => c.id), enemies: [{ templateId: enemy, count: 1 }] }), "Battle started")}><Swords />Start battle</button></div></Panel> }

function Characters({ data, run }: { data: Character[]; run: any }) { const [open, setOpen] = useState(false); return <Panel title="Character roster" icon={Users}>{open ? <EntityForm title="Create character" submit="Create character" onCancel={() => setOpen(false)} onSubmit={(f) => run(() => createCharacterAction(characterInput(f)), "Character created")} /> : <button className="btn primary m-4" onClick={() => setOpen(true)}><Plus />New character</button>}<div className="data-list">{data.map(c => <div className="roster-card" key={c.id}><div className="flex items-center justify-between"><div><span className="eyebrow">{c.isNpc ? "NPC" : "PLAYER"} · {RARITY_LABEL[c.rarity]}</span><h3>{c.name}</h3></div><button className={`btn ${c.inParty ? "primary" : "secondary"}`} onClick={() => run(() => setPartyAction(c.id, !c.inParty), c.inParty ? "Removed from party" : "Added to party")}>{c.inParty ? "In party" : "Add to party"}</button></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Resource label="HP" value={c.currentHp} max={c.maxHp} tone="hp" /><Resource label="TP" value={c.currentTp} max={c.maxTp} tone="tp" /><div className="mini-stat"><span>ATK</span><strong>{fmt(c.final.atk)}</strong></div><div className="mini-stat"><span>DEF</span><strong>{fmt(c.final.def)}</strong></div></div><div className="mt-4 flex flex-wrap gap-1">{c.tags.map(t => <span className="tag" key={t}>{t}</span>)}<span className="tag">{c.abilities.length} abilities</span></div></div>)}</div></Panel> }
function Enemies({ data, run }: { data: EnemyTemplate[]; run: any }) { const [open, setOpen] = useState(false); return <Panel title="Enemy templates" icon={Target}>{open ? <EntityForm title="Create enemy template" submit="Create enemy" onCancel={() => setOpen(false)} onSubmit={(f) => run(() => createEnemyAction(enemyInput(f)), "Enemy template created")} /> : <button className="btn primary m-4" onClick={() => setOpen(true)}><Plus />New enemy</button>}<div className="data-list">{data.map(e => <div className="roster-card" key={e.id}><div className="flex items-center justify-between"><div><span className="eyebrow">{RARITY_LABEL[e.rarity]} · TEMPLATE</span><h3>{e.name}</h3></div><span className="tag">LV {e.level}</span></div><div className="mt-4 grid grid-cols-3 gap-3"><div className="mini-stat"><span>HP</span><strong>{fmt(e.hp)}</strong></div><div className="mini-stat"><span>ATK</span><strong>{fmt(e.atk)}</strong></div><div className="mini-stat"><span>EXP</span><strong>{fmt(e.expReward)}</strong></div></div><div className="mt-4 flex gap-1">{e.tags.map(t => <span className="tag" key={t}>{t}</span>)}</div></div>)}</div></Panel> }
function Inventory({ data, run, goldCurrencyId }: { data: InventoryEntry[]; run: any; goldCurrencyId: string }) { return <Panel title="Owned items" icon={Backpack}><div className="data-list">{data.map(i => <div className="entity-row" key={i.id}><div className="item-glyph"><Backpack /></div><div className="flex-1"><div className="flex justify-between"><span className="font-semibold">{i.item.name}</span><span className={RARITY_TEXT[i.item.rarity]}>{i.item.rarity}★</span></div><div className="mt-1 text-xs text-muted-foreground">{i.item.category} · sell {fmt(Math.floor(i.item.value * .8))} each</div></div><div className="flex items-center gap-1"><button className="icon-btn" onClick={() => run(() => setInventoryQuantityAction(i.id, i.quantity - 1), "Quantity reduced")}><Minus /></button><span className="w-8 text-center tnum font-semibold">{i.quantity}</span><button className="icon-btn" onClick={() => run(() => addToInventoryAction(i.item.id, 1), "Item added")}><Plus /></button>{i.item.sellable && <button className="btn secondary" onClick={() => run(() => sellAction(i.id, 1, goldCurrencyId), `Sold ${i.item.name}`)}>Sell</button>}</div></div>)}</div></Panel> }
function Shop({ data, run }: { data: ShopEntry[]; run: any }) { const [quantities, setQuantities] = useState<Record<string, number>>({}); return <Panel title="Supply exchange" icon={ShoppingBag}><div className="data-list">{data.filter(e => e.available).map(e => { const qty = quantities[e.id] ?? 1; return <div className="roster-card" key={e.id}><div className="flex justify-between"><div><span className="eyebrow">AVAILABLE STOCK</span><h3>{e.item?.name ?? `${e.grantCurrencyAmount} currency units`}</h3><p className="mt-1 text-xs text-muted-foreground">{e.description}</p></div><span className="price">{fmt(e.price)} <small>credits</small></span></div><div className="mt-4 flex items-center gap-2"><input aria-label={`Quantity for ${e.item?.name ?? "listing"}`} className="field w-20" type="number" min="1" value={qty} onChange={x => setQuantities({ ...quantities, [e.id]: Math.max(1, Number(x.target.value)) })} /><button className="btn primary" onClick={() => run(() => purchaseAction(e.id, qty), `Purchased ${qty}x`)}>Buy {qty} <ArrowRight /></button></div></div> })}</div></Panel> }
function Gacha({ data, run }: { data: Data; run: any }) { const { gacha } = data; const [count, setCount] = useState(1); return <><Panel title="Summoning pool" icon={Sparkles}><div className="gacha-hero"><div><span className="eyebrow">ONE POOL · CONFIGURABLE ODDS</span><h2>Roll the unknown.</h2><p>Results enter the shared inventory immediately.</p></div><div className="flex flex-wrap gap-2"><button className="btn secondary" onClick={() => run(() => resetPityAction(), "Pity reset")}><RotateCcw />Reset pity</button><button className="btn secondary" onClick={() => run(() => pullAction(10), "Ten pulls resolved")}>Pull 10</button><input aria-label="Custom pull count" className="field w-20" type="number" min="1" max="100" value={count} onChange={e => setCount(Math.max(1, Math.min(100, Number(e.target.value))))} /><button className="btn primary" onClick={() => run(() => pullAction(count), `${count} pull${count === 1 ? "" : "s"} resolved`)}><Sparkles />Pull · {gacha.cost.perPull * count} orb</button></div></div><div className="mt-5 grid grid-cols-5 gap-2">{([1, 2, 3, 4, 5] as const).map(r => <div className="odds" key={r}><span className={RARITY_TEXT[r]}>{r}★</span><strong>{gacha.config.distribution[r]}%</strong></div>)}</div></Panel><div className="two-col"><Panel title="Pity counters" icon={Crown}><div className="space-y-4"><Resource label="4★ guarantee" value={gacha.pity.pity4} max={gacha.config.pity4Threshold} tone="exp" /><Resource label="5★ guarantee" value={gacha.pity.pity5} max={gacha.config.pity5Threshold} tone="exp" /></div></Panel><Panel title="Pool entries" icon={Sparkles}><div className="space-y-2">{gacha.pool.slice(0, 12).map(p => <div className="flex justify-between text-sm" key={p.id}><span>{p.name}</span><span className={RARITY_TEXT[p.rarity]}>{p.rarity}★</span></div>)}</div></Panel></div></> }
function HistoryView({ events, run }: { events: GameEvent[]; run: any }) { return <Panel title="Event chronicle" icon={ScrollText}><div className="event-list">{events.map(e => <div className="event" key={e.id}><span className="event-mark" /><div className="flex-1"><p>{e.description}</p><span>{eventTimestamp(e.createdAt)} · {e.type}</span></div>{e.undoable && <button className="btn secondary" onClick={() => run(() => undoEventAction(e.id), "Event undone")}>Undo</button>}</div>)}</div></Panel> }
